apiVersion: v1
data:
  api-key: YmVkcm9jay1nYXRld2F5LWludGVybmFsLWtleS0yMDI2
kind: Secret
metadata:
  creationTimestamp: "2026-02-10T03:12:58Z"
  name: bedrock-gateway-secret
  namespace: rag-system
  resourceVersion: "192666012"
  uid: f8ee2c78-d4a0-4b13-a509-6f33ce08b211
type: Opaque
