# PersistentVolumeClaims para RAG System
#
# IMPORTANTE: Antes de aplicar cambios en PVCs existentes:
# 1. Hacer backup de los datos
# 2. Proteger los PVs existentes: kubectl patch pv <pv-name> -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'
#
---
# Qdrant - Base de datos vectorial (datos críticos)
# Usa gp3-retain: expansión habilitada, datos protegidos, buen I/O
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage
  namespace: rag-system
  labels:
    app: qdrant
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-delete  # GP3 con expansión, cleanup automático (backups via Velero)
---
# OpenWebUI - Aplicación principal
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-storage
  namespace: rag-system
  labels:
    app: open-webui
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-delete  # GP3 con expansión, cleanup automático (backups via Velero)
