apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: rag-system
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        # Configuración básica
        - name: WEBUI_AUTH
          value: "True"
        - name: WEBUI_NAME
          value: "RAG System"
        
        # Configuración de Pipelines (sistema de pipelines personalizados)
        - name: PIPELINES_URLS
          value: "http://pipelines-service:9099"

        # Configuración LLM primario (Qwen 2.5 14B)
        - name: OPENAI_API_BASE_URL
          value: "http://simplevllm-svc.simplevllm.svc.cluster.local:8000/v1"
        - name: OPENAI_API_KEY
          value: "sk-dummy-key"
        - name: DEFAULT_MODELS
          value: "Qwen/Qwen2.5-14B-Instruct"
        
        # Configuración Vector DB (Qdrant)
        - name: VECTOR_DB
          value: "qdrant"
        - name: QDRANT_URI
          value: "http://qdrant-service:6333"
        
        # Configuración Embeddings
        - name: RAG_EMBEDDING_ENGINE
          value: "openai"
        - name: RAG_EMBEDDING_MODEL
          value: "Qwen/Qwen3-Embedding-0.6B"
        - name: RAG_OPENAI_API_BASE_URL
          value: "https://qwen-embedding.test.arba.gov.ar/v1"
        - name: RAG_OPENAI_API_KEY
          value: "sk-dummy-key"

        # Configuración Reranker
        - name: RAG_RERANKING_MODEL
          value: "BAAI/bge-reranker-v2-m3"
        - name: RERANKING_API_BASE_URL
          value: "http://rerank-baai-service.rerankers.svc.cluster.local/rerank"
        
        # Configuración RAG mejorada
        - name: CHUNK_SIZE
          value: "1000"
        - name: CHUNK_OVERLAP
          value: "200"
        - name: RAG_TOP_K
          value: "20"
        - name: ENABLE_RAG_HYBRID_SEARCH
          value: "True"
        - name: ENABLE_RAG_WEB_LOADER
          value: "True"
        - name: PDF_EXTRACT_IMAGES
          value: "True"
        
        # URL del servicio LlamaIndex (para pipelines personalizados)
        #- name: LLAMAINDEX_API_URL
        #  value: "http://llamaindex-api-service:8000"

        # Configuración PostgreSQL (para escalado horizontal)
        - name: DATABASE_URL
          value: "postgresql://ragsystemuser:rag322wq@10.16.25.12:5432/ragsystemdb"

        # Configuración Redis (WebSocket y cache para múltiples réplicas)
        - name: WEBSOCKET_MANAGER
          value: "redis"
        - name: WEBSOCKET_REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-config
              key: websocket-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-config
              key: cache-url

        # Secret key compartida entre réplicas
        - name: WEBUI_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: openwebui-secret
              key: secret-key

        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: storage
          mountPath: /app/backend/data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: openwebui-storage
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: rag-system
  labels:
    app: open-webui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: open-webui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui-ingress
  namespace: rag-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Sticky sessions para WebSocket (mejora la experiencia con múltiples réplicas)
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
  - host: asistente.test.arba.gov.ar
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui-service
            port:
              number: 80
