apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: rag-system
  labels:
    app: open-webui
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      serviceAccountName: openwebui-bedrock-sa
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        # Configuración básica
        - name: WEBUI_AUTH
          value: "True"
        - name: WEBUI_NAME
          value: "RAG System"
        - name: OPENAI_API_BASE_URL
          value: "http://bedrock-gateway.rag-system.svc.cluster.local:80/api/v1"
        - name: OPENAI_API_KEY
          value: "bedrock-gateway-internal-key-2026"
        # Configuración de Pipelines (sistema de pipelines personalizados)
        - name: PIPELINES_URLS
          value: "http://pipelines-service:9099"
        
        # Configuración Vector DB (Qdrant)
        - name: VECTOR_DB
          value: "qdrant"
        - name: QDRANT_URI
          value: "http://qdrant-service:6333"
       
        # URL del servicio LlamaIndex (para pipelines personalizados)
        #- name: LLAMAINDEX_API_URL
        #  value: "http://llamaindex-api-service:8000"

        # Configuración PostgreSQL (para escalado horizontal)
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: database-url

        # Secret key
        - name: WEBUI_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: openwebui-secret
              key: secret-key

        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: storage
          mountPath: /app/backend/data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: openwebui-storage
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: rag-system
  labels:
    app: open-webui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: open-webui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui-ingress
  namespace: rag-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - asistente.tecnicos.org.ar
    secretName: openwebui-tls
  rules:
  - host: asistente.tecnicos.org.ar
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui-service
            port:
              number: 80
