apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines
    app.kubernetes.io/part-of: rag-system
  name: pipelines
  namespace: rag-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pipelines
    spec:
      # 1. El Init Container corre como ROOT para poder instalar sin problemas
      initContainers:
      - name: install-deps
        image: python:3.11-slim
        command:
        - sh
        - -c
        - |
          pip install --target=/pip_libs psycopg2-binary qdrant-client openai pydantic
        volumeMounts:
        - mountPath: /pip_libs
          name: python-libs
      containers:
      - name: pipelines
        image: ghcr.io/open-webui/pipelines:main
        env:
        # 2. LE DECIMOS A PYTHON DONDE ESTÁN LAS LIBRERÍAS NUEVAS
        - name: PYTHONPATH
          value: "/pip_libs"
        - name: PIPELINES_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: pipelines-secret
        - name: DATABASE_URL
          value: "postgresql://ragsystemuser:admin123@postgres:5432/colegio_tecnicos"
        - name: BEDROCK_URL
          value: "http://bedrock-gateway.rag-system.svc.cluster.local:80"
        - name: BEDROCK_API_KEY
          valueFrom:
            secretKeyRef:
              name: bedrock-gateway-secret
              key: api-key
        - name: BEDROCK_MODEL
          value: "us.anthropic.claude-sonnet-4-20250514-v1:0"
        - name: QDRANT_URL
          value: "http://qdrant-service.rag-system.svc.cluster.local:6333"
        - name: QDRANT_COLLECTION
          value: "actas_colegio"
        ports:
        - containerPort: 9099
          name: http
        volumeMounts:
        - mountPath: /app/pipelines
          name: pipelines-data
        - mountPath: /pip_libs
          name: python-libs
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
      volumes:
      - name: pipelines-data
        persistentVolumeClaim:
          claimName: pipelines-storage
      # 3. Volumen temporal para compartir las librerías entre contenedores
      - name: python-libs
        emptyDir: {}