apiVersion: apps/v1
kind: Deployment
metadata:
  name: docling-gpu
  namespace: rag-system
spec:
  replicas: 0
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: docling
      variant: gpu
  template:
    metadata:
      labels:
        app: docling
        variant: gpu
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        node-type: gpu
      tolerations:
      - key: role
        operator: Equal
        value: gpu
        effect: NoSchedule
      containers:
      - name: docling
        image: 982170164096.dkr.ecr.us-east-2.amazonaws.com/docling-serve-gpu:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
          name: http
        env:
        - name: DOCLING_OCR_ENGINE
          value: rapidocr          # GPU-accelerated via onnxruntime-gpu
        - name: DOCLING_OCR_LANG
          value: spa,eng
        - name: DOCLING_SERVE_ENABLE_CUDA
          value: "1"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
        - name: DOCLING_SERVE_MAX_SYNC_WAIT
          value: "600"
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
            nvidia.com/gpu: 1
          limits:
            cpu: "2"
            memory: 6Gi
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: docling
  namespace: rag-system
spec:
  selector:
    app: docling
  ports:
  - port: 5001
    targetPort: http
