apiVersion: apps/v1
kind: Deployment
metadata:
  name: docling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docling
  template:
    metadata:
      labels:
        app: docling
    spec:
      runtimeClassName: nvidia
      imagePullSecrets:
      - name: harbor-secret
      nodeSelector:
        kubernetes.io/hostname: infra-ia02
      tolerations:
      - key: role
        operator: Equal
        value: gpu
        effect: NoSchedule
      securityContext:
        runAsUser: 0
      containers:
      - name: docling
        image: registry.arba.gov.ar/infraestructura/docling-serve-cu126:latest  
        imagePullPolicy: Always        
        ports:
        - containerPort: 5001
          name: http
        env:
        - name: DOCLING_ROCR_VERBOSE
          value: "1"
        - name: DOCLING_OCR_ENGINE
          value: rapidocr
        - name: DOCLING_OCR_LANG
          value: spa,eng
        - name: DOCLING_SERVE_ENABLE_CUDA
          value: "1"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
        resources:
          requests:
            cpu: 250m
            memory: 2Gi
            nvidia.com/gpu: 1
          limits:
            cpu: "2"
            memory: 4Gi
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: docling
spec:
  selector:
    app: docling
  ports:
  - port: 5001
    targetPort: http
