apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: rag-system
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        command:
        - redis-server
        args:
        # Configuración para uso stateless (sin persistencia)
        - --save ""                      # Deshabilitar snapshots RDB
        - --appendonly no                # Deshabilitar AOF
        - --maxmemory 512mb              # Límite de memoria
        - --maxmemory-policy allkeys-lru # Evict keys cuando se alcanza el límite
        - --tcp-backlog 511
        - --timeout 0
        - --tcp-keepalive 300
        # Seguridad básica
        - --protected-mode yes
        - --bind 0.0.0.0
        # Opcional: descomentar si quieres password
        # - --requirepass YOUR_PASSWORD_HERE
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: rag-system
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
