# PostgreSQL - Base de datos relacional (datos críticos)
# Usa gp3-retain: expansión habilitada, datos protegidos, buen I/O
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-storage
  namespace: rag-system
  labels:
    app: postgresql
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Aumentado de 10Gi para evitar quedarse sin espacio
  storageClassName: gp3-retain  # GP3 con expansión + Retain policy
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: rag-system
type: Opaque
stringData:
  postgres-password: "admin123"
  postgres-user: "ragsystemuser"
  postgres-password-user: "rag322wq"
  postgres-db: "ragsystemdb"
  # URL de conexión completa para Open WebUI
  database-url: "postgresql://ragsystemuser:rag322wq@postgres:5432/ragsystemdb"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: rag-system
  labels:
    app: postgresql
spec:
  serviceName: postgresql-service
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:16-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        env:
        # Password del usuario postgres (superusuario)
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-password

        # Usuario de aplicación
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-user

        # Password del usuario de aplicación
        - name: POSTGRES_PASSWORD_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-password-user

        # Base de datos inicial
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-db

        # Configuración de encoding
        - name: POSTGRES_INITDB_ARGS
          value: "--encoding=UTF8 --locale=C"

        # Configuración de performance
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"

        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d

        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-storage
      - name: init-script
        configMap:
          name: postgresql-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init
  namespace: rag-system
data:
  init-user.sh: |
    #!/bin/bash
    set -e

    # Crear usuario y base de datos si no existen
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      -- Verificar y crear extensiones necesarias
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
      CREATE EXTENSION IF NOT EXISTS "pg_trgm";

      -- Configuración de timezone
      SET timezone = 'America/Argentina/Buenos_Aires';

      -- Grants para el usuario de aplicación
      GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
      GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRES_USER;
      GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_USER;

      -- Configuración de búsqueda full-text
      ALTER DATABASE $POSTGRES_DB SET default_text_search_config = 'pg_catalog.spanish';
    EOSQL

    echo "PostgreSQL initialization completed successfully"
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: rag-system
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: postgresql
  # Para StatefulSet, mantener la IP estable
  clusterIP: None
---
# Service adicional con ClusterIP para acceso desde la aplicación
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: rag-system
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: postgresql
